# Generated by Django 6.0.1 on 2026-02-12 21:30

import django_magic_authorization.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_magic_authorization", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accesstoken",
            name="token",
            field=models.CharField(
                default=django_magic_authorization.models._gen_token,
                max_length=64,
                unique=True,
            ),
        ),
    ]
