# Generated by Django 6.0.1 on 2026-02-12 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_magic_authorization", "0002_alter_accesstoken_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="accesstoken",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="accesstoken",
            name="max_uses",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
